server:
  port: 90

discord:
  token:
  activity:
    playing: 개발중인 봇입니다.

api:
  key:
    covid:


spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://needon.kr/admin_discord?useUnicode=true&characterEncoding=utf-8
    username:
    password:

  jpa:
    database: mysql
    hibernate:
      ddl-auto: update
      naming:
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
        physical-strategy: kr.needon.needonbot.core.config.NamingStrategy
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
