server:
  port: 90

discord:
  token: OTI5OTA3MzI0MjI1NzMyNjE4.YduJrg.tJZN9K5hMe3TVZSuF1qzh45S-_Q
  activity:
    playing: 개발중인 봇입니다.


spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url:
    username:
    password:

  jpa:
    database: mysql
    hibernate:
      ddl-auto: update
      naming:
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
        physical-strategy: kr.needon.needonbot.core.config.NamingStrategy
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
